#!/usr/bin/env python3
"""Generate src/hardware/su2000/m88110_ops.inc (C++ decode table) from tools/m88110_ops.py (MAME, BSD-3)."""
import os, re
from m88110_ops import OPS
out = os.path.join(os.path.dirname(__file__), '..', '..', 'src', 'hardware', 'su2000', 'm88110_ops.inc')
names = []
for v, m, n, a in OPS:
    if n not in names: names.append(n)
ident = lambda n: 'OP_' + re.sub(r'[^A-Za-z0-9]', '_', n).upper()
with open(out, 'w') as o:
    o.write('/* Generated by su2000/tools/gen_m88110_inc.py from the MAME mc88110 disassembler table\n'
            ' * (src/devices/cpu/m88000/m88000d.cpp, BSD-3-Clause, copyright-holders AJR). Do not edit. */\n')
    o.write('#ifdef M88110_ENUM\n' + ''.join(f'    {ident(n)},\n' for n in names) + '#endif\n')
    o.write('#ifdef M88110_NAMES\n' + ''.join(f'    "{n}",\n' for n in names) + '#endif\n')
    o.write('#ifdef M88110_TABLE\n' + ''.join(f'    {{ 0x{v:08x}u, 0x{m:08x}u, {ident(n)}, AM_{a} }},\n' for v, m, n, a in OPS) + '#endif\n')
print(len(names), 'mnemonics', len(OPS), 'entries ->', os.path.normpath(out))
